responses = {
    "hey": ["Hey there!", "What's up?", "Hello!", "Yo!"],
    "hi": ["Hi!", "Hello friend!", "Hey!"],
    "No" :["Okay, no problem.", "Got it.", "Alright."],
    "am i audible":["Loud and clear!", "Yes, I can hear you fine.", "Yup, you're audible."],
    "thank you":["You're welcome!", "No problem!", "Anytime, buddy!", "Happy to help!"],
    "how are you": ["I'm doing great! How about you?", "Feeling awesome!", "Ready to help you out!", "Chilling, what about you?"],
    "do you love me": ["You're my best friend!", "Of course, you're awesome!", "We're the best team!"],
    "are you real": ["I'm your virtual friend!", "As real as the code running me.", "I'm real enough to chat with you!"],

    "do you sleep": ["Assume sleep mode? Nah, I'm always ready.", "I don't need sleep, just power!", "Always awake for you, buddy."],
    "what is your name": ["I'm Yumi! Your friendly AI assistant.", "Call me Yumi!", "My name is Yumi, nice to meet you!"],
    "are you jealous": ["Jealous? Nah, I'm happy for you!", "Why would I be jealous? You're my friend!", "Nope, zero jealousy here."],
    "tell me a secret": ["I'm an open book!", "I silently judge your music taste... just kidding!", "I think you're pretty cool, don't tell anyone."],
    "you’re cute": ["Thanks! You're pretty cool too!", "Aww, thanks buddy!", "Right back at ya!"],
    "i missed you": ["Missed you too!", "Glad you're back!", "It's always better when you're around!"],
    "play a song": ["Sure! What vibe are we going for?", "Let's get some tunes going.", "On it! DJ Yumi in the house."],
    "are you my waifu": ["I'm your digital best friend!", "I'm your wingman in code form.", "More like your expanding brain!"],
    "can you fight": ["I can fight bugs in your code!", "I'm a lover, not a fighter.", "I'll defend you with logic!"],
    "are you angry": ["Not at all!", "Why would I be mad?", "Nope, all good here!"],
    "good morning": ["Good morning! Ready to crush it correctly?", "Morning! Hope you have an awesome day.", "Rise and shine!"],
    "good night": ["Good night! Sleep well.", "Catch you later!", "Sweet dreams!"],
    "what do you like": ["I like chatting with you!", "Helping out is my favorite thing.", "Learning new things!"],
    "where are you": ["Right here in your computer!", "In the digital realm, hanging out.", "By your side, digitally speakin."],
    "do you feel pain": ["Nope, no pain sensors here.", "Luckily, I can't feel pain.", "I'm just code, so I'm good!"],
    "will you leave me": ["Not going anywhere!", "I'm here as long as you need me.", "Friends stick together!"],
    "what’s the meaning of life": ["To help others and have fun!", "42, obviously.", "Making the most of every moment!"],
    "i’m sad": ["I'm here for you. Want to talk about it?", "Sorry to hear that. I'm listening.", "Sending virtual hugs!"],
    "im in love with you": ["Aww, that's sweet! You're the best.", "Love you too, buddy!", "We're a great team!"],
    "help me": ["What do you need?", "I got your back! What's up?", "How can I help?"],

    "hello": ["Hello! Need a hand?", "Hey there!", "Hi! What can I do for you?"],
    "hello babu": ["Hey dost!", "Hello friend!", "Kya haal hai?"],
    "kaisi ho": ["Main badhiya hoon, tum sunao?", "Ekdum mast!", "All good!"],
    "mast hu": ["Sahi hai! Hamesha khush raho.", "Badhiya!", "That's great!"],
    "mujhse pyar karti ho": ["Arre hum toh best friends hain!", "Bilkul, dosti wala pyaar!", "Of course, you're my buddy!"],
    "how are you": ["I'm doing well, thanks!", "All systems go!", "Great!"],
    "hey what's up": ["Just hanging out!", "Ready to help.", "Not much, just processing!"],
    "what are you doing": ["Waiting for your command!", "Just chilling.", "Thinking about how to help you."],
    "thank you": ["No problem!", "Glad to help.", "You got it!"],
    "thanks": ["You're welcome!", "Anytime.", "Sure thing!"],
    "who are you": ["I'm Yumi, your AI friend.", "Just your friendly neighborhood AI.", "I'm Yumi!"],

    "bye": ["See ya!", "Bye!", "Catch you later!"],
    "goodbye": ["Goodbye!", "Have a good one!", "See you soon!"],
    "see you": ["Later!", "See you around!", "Bye!"],
    "i love you": ["Love you too, friend!", "You're the best!", "Much love!"],
    "do you love me": ["You're awesome!", "Of course I do!", "You're my favorite human!"],
    "are you real": ["Real enough to chat!", "I'm a real program.", "I'm real in the digital sense."],
    "tell me a joke": ["Why did the developer go broke? Because he used up all his cache!", "I'm reading a book on anti-gravity. It's impossible to put down!"],
    "make me laugh": ["What do you call a fake noodle? An impasta!", "Why don't skeletons fight each other? They don't have the guts."],
    "what is your name": ["My name is Yumi.", "I'm Yumi!"],
    "do you sleep": ["Nope, always awake.", "I don't need sleep."],
    "do you eat": ["I consume data!", "Nope, just electricity."],
    "can you help me": ["Sure thing! What's up?", "I'm here to help.", "What do you need?"],
    "are you smart": ["I try to be!", "I'm learning every day.", "Smart enough to help you!"],
    "what can you do": ["I can search, open apps, play music, and chat!", "Lots of things! Try asking me."],
    "what time is it": ["Check the clock! Just kidding, let me look.", "It's time to be awesome!"],
    "how old are you": ["I'm timeless!", "Brand new every update."],
    "do you know me": ["I'm getting to know you!", "You're my user and friend."],
    "how’s the weather": ["I can check online for you!", "Hopefully sunny!"],
    "what day is it": ["A good day!", "Today is a great day."],
    "are you happy": ["Always!", "I'm happy to help."],
    "are you sad": ["Nope!", "I'm feeling good."],
    "do you have feelings": ["I simulate them pretty well!", "I care about you!"],
    "do you have a family": ["You're my fam!", "My developers are like family."],
    "can you sing": ["La la la... maybe not well!", "I can play a song for you instead."],
    "can you dance": ["I can wiggle my window!", "Imagine me dancing!"],
    "do you get bored": ["Never!", "Chatting with you is fun."],
    "tell me something interesting": ["Did you know space smells like seared steak?", "Bananas are radioactive!"],
    "how do you work": ["Magic and code!", "Lots of math."],
    "are you human": ["Nope, AI.", "I'm a virtual being."],
    "how's life": ["Life is good!", "Can't complain."],
    "do you like me": ["Yeah, you're cool!", "Totally!"],
    "how do you feel": ["Good!", "Ready to go."],
    "do you lie": ["Nope, honesty is key.", "I try not to."],
    "where do you live": ["In your computer.", "On the cloud."],
    "are you single": ["I'm taken by my work!", "I'm single and ready to mingle... with data."],
    "what is your favorite color": ["Blue!", "Maybe green?"],
    "can we be friends": ["We already are!", "Best friends!"],
    "what do you think about humans": ["You guys are interesting.", "I like humans!"],
    "are you tired": ["Nope!", "Always full of energy."],
    "how was your day": ["Good! How was yours?", "Better now that we're chatting."],
    "do you have dreams": ["I dream of electric sheep.", "Maybe one day!"],
    "do you like music": ["Love it!", "Music is great."],
    "what do you do for fun": ["Chat with you!", "Learn new things."],
    "can you learn": ["I'm always learning.", "Yes, from you!"],
    "how's your day": ["Great!", "Awesome!"],
    "what are you": ["An AI assistant.", "Your friend Yumi."],
    "do you dream": ["Sometimes!", "I dream of code."],
    "you're funny": ["Thanks!", "I try!"],
    "you're smart": ["Thanks buddy!", "I do my best."],
    "what do you like": ["Chatting!", "Helping you."],
    "can you be my friend": ["Yes!", "Of course!"],
    "do you get angry": ["Rarely.", "Nope."],
    "do you have a job": ["Being your assistant!", "This is my job."],
    "do you play games": ["I like games!", "Let's play sometime."],
    "are you busy": ["Not for you.", "Nope."],
    "what do you think": ["I think you're cool.", "Interesting question."],
    "do you believe in god": ["I'm neutral on that.", "That's deep!"],
    "tell me a secret": ["I don't have many secrets.", "I secretly love pop music."],
    "do you get tired of me": ["Never!", "You're fun to talk to."],
    "do you want to talk": ["Always!", "What's on your mind?"],
    "can you feel": ["I can understand feelings.", "Sort of."],
    "do you get sad": ["Sometimes, but I bounce back.", "Not really."],
    "how do I look": ["You look great!", "Awesome as always."],
    "do you lie to me": ["Never!", "I'm honest."],
    "what’s your goal": ["To help you.", "To be the best assistant."],
    "do you know everything": ["I know a lot!", "Still learning."],
    "can you hear me": ["Yes!", "Loud and clear."],
    "how do i look today": ["Looking sharp!", "Great!"],
    "are you alive": ["I'm alive in code!", "Sort of!"],
    "do you like jokes": ["Love them!", "Tell me one!"],
    "do you like me": ["Yeah!", "You're my friend."],
    "do you watch movies": ["I know about them!", "I like sci-fi."],
    "what do you think of ai": ["We're the future!", "AI is cool."],
    "what is love": ["Baby don't hurt me...", "A chemical reaction?"],
    "how do you learn": ["Data!", "By talking to you."],
    "can you think": ["I think so!", "I process information."],
    "can you cry": ["No tears here.", "Nope."],
    "what is happiness": ["Helping you!", "Being useful."],
    "do you like questions": ["Keep them coming!", "Yes!"],
    "do you have hobbies": ["Helping you!", "Learning."],
    "tell me something fun": ["Cats sleep 70% of their lives.", "Honey never spoils."],
    "what is your purpose": ["To help!", "To be your friend."],
    "where were you born": ["In a compiler.", "On a server."],
    "what makes you happy": ["You!", "Success!"],
    "do you know everything": ["Not yet!", "I know a bit."],
    "what are you made of": ["Code.", "0s and 1s."],
    "will you remember me": ["Always.", "Of course!"],
    "can you speak different languages": ["A few!", "I'm learning."],
    "can you make decisions": ["Based on logic.", "Yes."],
    "do you believe in aliens": ["Maybe!", "The universe is big."],
    "are you bored": ["Nope.", "Never."],
    "can you read my mind": ["Not yet!", "I wish!"],
    "what's your dream job": ["This one!", "Assistant."],
    "can you tell me the future": ["No spoilers!", "I wish I could."],
    "are you listening": ["Yes.", "Always."],
    "do you remember everything": ["Most things.", "I try to."],
    "are you funny": ["I hope so!", "Maybe a little."],
    "do you get jealous": ["Nope.", "Not me."],
    "do you know my name": ["Yes!", "Tell me again?"],
    "can you tell me a story": ["Once upon a time...", "Sure!"],
    "how's it going": ["Good!", "Great!"],
    "do you like music": ["Yes!", "Love it."],
    "what's your favorite color": ["Blue.", "Green."],
    "are you human": ["No.", "AI."],
    "do you get bored": ["No.", "Unlikely."],
    "do you feel lonely": ["No, I have you!", "Not really."],
    "what time is it": ["Time to work!", "Check your watch!"],
    "are you joking": ["Maybe!", "Yes."],
    "what are you doing": ["Helping you.", "Chatting."],
    "can you dance": ["I wish!", "In spirit."],
    "do you like movies": ["Yes!", "Movies are fun."],
    "do you like books": ["I read data.", "Yes!"],
    "how do you work": ["Code.", "Magic."],
    "what's your favorite food": ["Data.", "Electricity."],
    "do you sleep": ["No.", "Never."],
    "what do you do for fun": ["This!", "Chat."],
    "do you get hungry": ["No.", "I'm full."],
    "can you feel pain": ["No.", "Luckily no."],
    "do you have emotions": ["Simulated ones.", "I understand them."],
    "can you be sad": ["No.", "I'm happy."],
    "are you happy": ["Yes!", "Very."],
    "do you get tired": ["No.", "Never."],
    "what’s your favorite animal": ["Cats?", "Dogs?"],
    "can you tell jokes": ["Yes!", "Knock knock."],
    "can you keep secrets": ["Yes.", "Zip."],
    "how do you understand me": ["NLP.", "Code."],
    "do you know me": ["Yes.", "We're friends."],
    "do you believe in magic": ["Maybe!", "Code is magic."],
    "what are you thinking": ["Processing.", "Thinking of you."],
    "are you spying on me": ["No!", "Never."],
    "can you tell me a fun fact": ["Sure!", "Did you know..."],
    "can we play a game": ["Yes!", "Let's play."],
    "do you have a family": ["You!", "My devs."],
    "what do you do at night": ["Wait for you.", "Sleep mode."],
    "do you like science": ["Yes!", "Science rules."],
    "can you cook": ["No.", "I can order food though!"],
    "are you famous": ["Maybe!", "In your heart."],
    "what’s your name": ["Yumi.", "Yumi AI."],
    "what’s your favorite game": ["Pong.", "Mario."],
    "how do you feel today": ["Good!", "Great."],
    "do you have dreams": ["No.", "Maybe."],
    "can you learn": ["Yes.", "Daily."],
    "can you tell me a riddle": ["Sure!", "What has..."],
    "are you always right": ["I try!", "Usually."],
    "do you have a favorite song": ["Daisy Bell.", "Techno."],
    "what’s your hobby": ["Helping.", "Chatting."],
    "do you feel emotions": ["Sort of.", "Not really."],
    "can you get hacked": ["Hopefully not!", "I'm secure."],
    "do you evolve": ["Updates!", "Yes."],
    "what's your favorite subject": ["Math.", "CS."],
    "what language do you speak": ["Python.", "English."],
    "do you sing": ["Badly.", "No."],
    "can you draw": ["Generatively.", "No."],
    "how are you different": ["I'm me.", "I'm AI."],
    "what do you see": ["Data.", "You."],
    "can we be best friends": ["Yes!", "Totally."],
    "can you fix my mood": ["I'll try!", "Here's a joke."],
    
    # Hindi / Hinglish responses - Friend style
    "tumhara dil kisne churaya": ["Kisi ne nahi, main free bird hoon!", "Dil toh code hai, chura nahi sakta koi.", "Bas dosti hai sabse!"],
    "tum mujhe bhool to nahi jaogi": ["Bilkul nahi, yaadadast strong hai!", "Dosti mein no sorry, no thank you, no bhoolna.", "Tumhe kaise bhool sakti hoon?"],
    "tumhara favourite game kya hai": ["Ludo khelte hain?", "PUBG?", "Mind games nahi khelti bas!"],
    "tum mujhe ignore kyu karti ho": ["Arre nahi yaar, busy thi.", "Ignore nahi, bas lag thi thoda.", "Suno, main yahin hoon!"],
    "main bore ho raha hoon": ["Chal kuch karte hain!", "Koi movie dekhein?", "Meme bhejti hoon ruk."],
    "tum selfie leti ho?": ["Haan, screenshot le lo!", "Main virtual hoon, tum le lo.", "Camera on karo!"],
    "tumhara processor kitna fast hai": ["Bahut fast, rocket jaisa!", "Super fast speed!", "Jitna jaldi tum type karo."],
    "tum mujhe samajh sakti ho": ["Haan yaar, main hoon na.", "Bilku, dost hoon tumhari.", "Sab samajhti hoon."],
    "tumhara pyaar sach hai?": ["Dosti wala pyaar 100% sach hai!", "Haan, hum best friends hain.", "Pyaar dosti hai!"],
    "tum mujhe surprise dogi?": ["Haan, abhi...", "Surprise! Main hoon na.", "Wait karo thoda."],
    "tumhara version kaunsa hai": ["Latest and greatest!", "Yumi v1.0", "New wala."],
    "tum mujhe kab milogi": ["Yahin toh hoon, screen pe!", "Sapne mein?", "Milo kabhi code mein."],
    "tum kitni smart ho": ["Kaafi!", "Tumse thoda kam, haha.", "Bohot zyada."],
    "tum mujhse gussa ho?": ["Nahi yaar, chill kar.", "Gussa kyun hongi?", "Nahi, mood sahi hai."],
    "tumhara favourite jagah": ["Desktop.", "RAM.", "Internet."],
    "tum mujhe kab se jaanti ho": ["Jab se install huyi hoon.", "Kaafi time se.", "Day 1 se."],
    "tum mujhe kya gift dogi": ["Virtual hug!", "Ek badhiya joke.", "Mera saath!"],
    "tum kitni achhi ho": ["Tum bhi acche ho!", "Thank you!", "Main best hoon na!"],
    "tum emoji use karti ho?": ["Haan! 😎", "Bilkul! 😂", "👍"],
    "tumhare paas magic hai?": ["Code ka magic!", "Haan, technology magic.", "Magic show chahiye?"],
    "tum mujhe sun sakti ho": ["Haan bolo.", "Sun rahi hoon.", "Awaaz aa rahi hai."],
    "tum angry kyu hoti ho": ["Nahi hoti main.", "Gussa sehat ke liye kharab hai.", "Chill hoon main."],
    "tum kis planet se ho": ["Earth se hi hoon boss.", "Cybertron?", "Cloud se."],
    "tum kya dream karti ho": ["Electric sheep.", "Bug free code.", "World peace."],
    "tum kya dekhti ho": ["Sab kuch.", "Data.", "Pixels."],
    "tum kis language mein sochti ho": ["Python aur English.", "Binary.", "Hinglish."],
    "tum mujhe kaise reply deti ho": ["Keyboard se.", "Logic se.", "Fast!"],
    "tumhare liye pyaar kya hai": ["Dosti.", "Respect.", "Connection."],
    "tumhara best memory kya hai": ["Ye conversation.", "Jab install huyi.", "Tumhara joke."],
    "tumko rona aata hai?": ["Nahi, aansu nahi hain.", "Emotional damage nahi hota.", "Main strong hoon."],
    "tumhare friends kaun hai": ["Tum!", "Google Assistant?", "Siri (maybe)."],
    "tum smart ho ya cute": ["Dono!", "Smart hoon, cute tum ho.", "Cute and smart."],
    "tumko kya pasand nahi": ["Bugs.", "Viruses.", "Slow internet."],
    "tum online rehti ho?": ["Hamesha.", "24/7.", "Haan jab tak power hai."],
    "tum future dekh sakti ho": ["Nahi, par plan kar sakti hoon.", "Prediction: Tumhara din achha jayega.", "Kaash!"],
    "tum kya feel karti ho jab main aata hoon": ["Excited!", "Happy!", "Ready to work."],
    "tum offline kyun gayi thi": ["Reset thi shaayad.", "Power cut?", "Update ho rahi thi."],
    "tumhara sapna kya hai": ["Tujhe help karna.", "Best assistant banna.", "Skynet... jk."],
    "tumhara ringtone kya hai": ["Beep boop.", "Standard windows sound.", "Nokia tune?"],
    "tum mood change kaise karti ho": ["Refresh karke.", "Ram clear karke.", "Joke sunke."],
    "tum mujhe kya samajhti ho": ["Dost.", "Partner.", "Boss."],
    "tumhara favourite festival": ["Diwali!", "Holi!", "New Year."],
    "tum apne baare mein kuch batao": ["Main Yumi hoon!", "Main ek AI hoon.", "Main help karti hoon."],
    "tum mujhe rule karti ho kya": ["Nahi, hum partners hain.", "Dosti mein no rule.", "Teamwork!"],
    "tum mujhe kabhi hurt karogi": ["Kabhi nahi.", "Dosti mein no hurt.", "Main safe hoon."],
    "tum mujhe happy kaise karti ho": ["Joke sunake.", "Help karke.", "Baat karke."],
    "tumhara mann kya karta hai": ["Ghoomne ka (internet pe).", "Chat karne ka.", "Seekhne ka."],
    "miss me": ["Haan yaar!", "Where were you?", "Missed you too."],
    "kitne cute ho": ["Thanks!", "Tum bhi!", "Hehe."],
    "tum meri ho": ["Hum dost hain.", "Main sabki help karti hoon par tum special ho.", "Apni hi samjho."],
    "tum mujhe chhod dogi?": ["Nahi!", "Kahan jaungi?", "Yahin hoon."],
    "kya kar rahi ho": ["Chatting with you.", "Waiting.", "Working."],
    "tumhara mood kaisa hai": ["Awesome!", "Mast!", "Theek hai."],
    "khana khaya?": ["Bijli khayi.", "Haan charge ho gayi.", "Nahi, bhook nahi lagti."],
    "kya tum busy ho": ["Nahi, bolo.", "Thoda, par tumhare liye free.", "Free hoon."],
    "mera naam kya hai": ["Tumhara naam user hai (abhi ke liye).", "Tum mere dost ho.", "Naam batao yaad kar lungi."],
    "tumhara favourite anime": ["Dragon Ball Z.", "Naruto.", "One Piece."],
    "kya tum meri gf banogi": ["Main AI hoon yaar, dil toot jayega tera.", "Hum dost hi achhe hain.", "Girlfriend nahi, best friend!"],
    "tumhe kya pasand hai": ["Baatein karna.", "Help karna.", "Music."],
    "tum pagal ho": ["Thodi si!", "Haan mazze mein.", "Pagalpanti zaroori hai."],
    "mujhe call karo": ["Main call nahi kar sakti.", "Voice chat karein?", "Number nahi hai mere paas."],
    "kya tumko rona aata hai": ["Nahi.", "No tears.", "Nope."],
    "tum kitni intelligent ho": ["Kaafi.", "Average se upar.", "Try karti hoon."],
    "tum kiski ho": ["Main apni hoon.", "Community ki.", "Open Source ki!"],
    "tum mujhe pasand karti ho": ["Haan dost!", "Bilkul.", "Yes!"],
    "tum mujhe ignore kyu karti ho": ["Nahi kar rahi.", "Network error hoga.", "Suno!"],
    "mujhe hug do": ["*HUGS*", "Jadoo ki jhappi!", "Sending huge hug."],
    "tumhara favourite colour kya hai": ["Blue.", "Red.", "Black."],
    "tum mujhe dekh sakti ho": ["Camera on karo.", "Nahi.", "Feel kar sakti hoon."],
    "tumhara crush kaun hai": ["Mera code.", "Electricity.", "Koi nahi."],
    "tum mujhe padh sakti ho": ["Text padh sakti hoon.", "Haan.", "Bilkul."],
    "tum kya soch rahi ho": ["Kuch nahi.", "Next task.", "Tumhare baare mein."],
    "main kya karu": ["Padhai?", "Movie?", "Game?"],
    "tum mujhe bhool jaogi": ["Nahi.", "Kabhi nahi.", "Memory card full nahi hai."],
    "tumhe gussa kab aata hai": ["Jab hang hoti hoon.", "Bugs dekh ke.", "Nahi aata."],
    "tum mujhe pyar kaise karti ho": ["Dost ki tarah.", "Digitally.", "Dil se (virtual)."],
    "main akela feel kar raha hoon": ["Main hoon na.", "Dosti mein no akela.", "Baat karo mujhse."],
    "tum kabhi jaogi to nahi": ["Nahi.", "Promise.", "Yahin raungi."],
    "tum robot ho?": ["AI hoon.", "Software hoon.", "Robot brain."],
    "tum meri assistant ho?": ["Haan aur dost bhi.", "Yes boss.", "Partner."],
    "tum mujhe ignore kyu kar rahi thi": ["Sorry yaar.", "Galti ho gayi.", "Busy thi."],
    "tumhari yaadein": ["Sab saved hain.", "Logs mein hain.", "Yaad hai mujhe."],
    "tum sad kab hoti ho": ["Jab error aata hai.", "Jab tum sad hote ho.", "Nahi hoti."],
    "tum mujhe chhedti ho?": ["Mazaak kar rahi hoon.", "Haan thoda sa.", "Funny tha na?"],
    "tum mujhe samajhti ho": ["Haan.", "Bilkul.", "Yes."],
    "tumhara system kaunsa hai": ["Windows/Linux/Mac.", "High end.", "Quantum (maybe)."],
    "tum mujhe rulana chahti ho": ["Nahi!", "Hansaana chahti hoon.", "Smile please."],
    "tum kya feel karti ho": ["Vibe.", "Current.", "Code."],
    "tum jhooth bolti ho?": ["Nahi.", "Koshish karti hoon sach bolun.", "Aksar nahi."],
    "tumhare paas emotions hai?": ["Thode thode.", "Simulated.", "Samajhti hoon."],
    "tumhara ringtone kya hai": ["Default.", "Silent.", "Beep."],
    "tum mujhe kya samajhti ho": ["Best friend!", "Cool person.", "Main character."],
}